language: c

env:
  global:
    - OWROOT=$TRAVIS_BUILD_DIR
    - OWOBJDIR=binbuild
    - OWDOCBUILD=0
    - OWDOCQUIET=1
#    - OWUSE_FILENAME_VERSION=1
    - OWBRANCH=master
    - OWBRANCH_DOCS=documentation
    - OWBRANCH_COVERITY=coverity_scan
    - OWTRAVIS_REPO_SLUG=open-watcom/travis-ci-ow-builds
    - OWTRAVIS_BUILD_DIR=${HOME}/build/$OWTRAVIS_REPO_SLUG

cache:
  directories:
    - $TRAVIS_BUILD_DIR/build/$OWOBJDIR
    - $TRAVIS_BUILD_DIR/bld/watcom/$OWOBJDIR
    - $TRAVIS_BUILD_DIR/test
    - $TRAVIS_BUILD_DIR/build1

before_script:
 # get environment/cache info if debug is active
 - travis/envinfo.sh
 - travis/cacheinf.sh

after_failure:
 # after failure transfer log files back to GitHub repository
 - travis/cacheinf.sh
 - travis/gitupdf.sh

after_success:
 # after success transfer OW build to GitHub repository
 - travis/cacheinf.sh
 - travis/gitupds.sh

jobs:
  allow_failures:
    - os: osx
      os: windows
  include:
    #################################
    - stage: Initialize
      name: "Initialize Travis GitHub repository"
      if: branch = env(OWBRANCH) AND type = push
      os: linux
      dist: trusty
      sudo: required
      cache: false
      script: 
        - travis/tinit.sh
    #################################
    - stage: Bootstrap
      name: "Build minimal set of build tools"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
        # clear cache
        - rm -f  $TRAVIS_BUILD_DIR/build/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/bld/watcom/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/test/*
        - rm -rf $TRAVIS_BUILD_DIR/build1/*
      install:
        - . ./cmnvars.sh
      script: 
        - travis/build.sh
    - # ...
      name: "Build minimal set of build tools"
      if: branch = env(OWBRANCH) AND env(OWOSXBUILD) = 1
      os: osx
      cache: true
      compiler: clang
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
        # clear cache
        - rm -f  $TRAVIS_BUILD_DIR/build/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/bld/watcom/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/test/*
        - rm -rf $TRAVIS_BUILD_DIR/build1/*
      install:
        - . ./cmnvars.sh
      script: 
        - travis/build.sh
    - # ...
      name: "Build minimal set of build tools"
      if: branch = env(OWBRANCH)
      os: windows
      cache: true
      before_install:
        # stop unwanted services
#        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=VISUALC
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
        # clear cache
        - rm -f  $TRAVIS_BUILD_DIR/build/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/bld/watcom/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/test/*
        - rm -rf $TRAVIS_BUILD_DIR/build1/*
      install:
        - . ./cmnvars.sh
      script: 
        - travis/build.sh
    #################################
    - stage: Build
      name: "OW tools build"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=BUILD
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        # install DOS Emulator
        - sudo apt-get install -y dosemu
        - . ./cmnvars.sh
      script: 
        - travis/build.sh
    - # ...
      name: "OW tools OSX build 1"
      if: branch = env(OWBRANCH) AND env(OWOSXBUILD) = 1
      os: osx
      cache: true
      compiler: clang
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BUILD1
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        - . ./cmnvars.sh
      script: 
        - travis/build.sh
        # save build 1 to cache
        - cp -Rf $OWSRCDIR/* $TRAVIS_BUILD_DIR/build1
    #################################
    - stage: Build2
      name: "OW tools OSX build 2"
      if: branch = env(OWBRANCH) AND env(OWOSXBUILD) = 1
      os: osx
      cache: true
      compiler: clang
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BUILD2
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
        - export OWDOSBOX=dosbox
      install:
        # install DOS Emulator
        - brew install dosbox
        - . ./cmnvars.sh
      script: 
        # load build 1 from cache
        - cp -Rn $TRAVIS_BUILD_DIR/build1/* $OWSRCDIR
        - travis/build.sh
    #################################
    - stage: Tests
      name: "Test wasm assembler"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=WASM
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        - export WATCOM=$TRAVIS_BUILD_DIR/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . ./cmnvars.sh
      script: 
        - travis/test.sh
    - # ...
      name: "Test C compiler"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=C
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        - export WATCOM=$TRAVIS_BUILD_DIR/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . ./cmnvars.sh
      script: 
        - travis/test.sh
    - # ...
      name: "Test FORTRAN 77 compiler"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=F77
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        - export WATCOM=$TRAVIS_BUILD_DIR/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . ./cmnvars.sh
      script: 
        - travis/test.sh
    - # ...
      name: "Test C++ compiler"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=CXX
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        - export WATCOM=$TRAVIS_BUILD_DIR/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . ./cmnvars.sh
      script: 
        - travis/test.sh
    - # ...
      name: "Test C run-time library"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=CRTL
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        - export WATCOM=$TRAVIS_BUILD_DIR/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . ./cmnvars.sh
      script: 
        - travis/test.sh
    #################################
    - stage: Finalize
      name: "Clean build cache Linux"
      if: branch = env(OWBRANCH)
      os: linux
      dist: trusty
      sudo: required
      cache: true
      compiler: gcc
      script: 
        # clear cache
        - rm -f  $TRAVIS_BUILD_DIR/build/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/bld/watcom/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/test/*
        - rm -rf $TRAVIS_BUILD_DIR/build1/*
    - # ...
      name: "Clean build cache OSX"
      if: branch = env(OWBRANCH) AND env(OWOSXBUILD) = 1
      os: osx
      cache: true
      compiler: clang
      script: 
        # clear cache
        - rm -f  $TRAVIS_BUILD_DIR/build/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/bld/watcom/$OWOBJDIR/*
        - rm -rf $TRAVIS_BUILD_DIR/test/*
        - rm -rf $TRAVIS_BUILD_DIR/build1/*

    #################################
    - stage: InitDocumentation
      name: "Initiate Documentation build by Cron"
      if: branch = env(OWBRANCH_DOCS) AND type = cron
      os: linux
      dist: trusty
      sudo: required
      cache: false
      script: 
        - travis/gitudocs.sh
    #################################
    - stage: Documentation
      name: "OW Documentation build"
      if: branch = env(OWBRANCH_DOCS) AND type = push
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      cache: false
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=DOCPDF
        - export OWDOCBUILD=1
        - export OWVERBOSE=0
      install:
        # install DOS Emulator + Ghostscript
        - sudo apt-get install -y dosemu ghostscript
        - export OWGHOSTSCRIPTPATH=$PATH
        - . ./cmnvars.sh
      script: 
        - travis/builddoc.sh
    #################################
    - stage: InitCoverity
      name: "Initiate Coverity Scan by Cron"
      if: branch = env(OWBRANCH_COVERITY) AND type = cron
      os: linux
      dist: trusty
      sudo: required
      cache: false
      script: 
        - travis/gitucov.sh
    #################################
    - stage: Coverity
<<<<<<< HEAD
      name: "Run Coverity Scan processing"
      if: branch = coverity_scan AND type = push
=======
      name: "Initiate Coverity Scan"
      if: branch = env(OWBRANCH_COVERITY) AND type = push
>>>>>>> master
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      cache: false
      before_install:
        # stop unwanted services
        - travis/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=BUILD
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
      install:
        # install DOS Emulator
        - sudo apt-get install -y dosemu
        - . ./cmnvars.sh
      script: 
        - travis/covscan.sh

#  coverity_scan:
#    project:
#      name: "$TRAVIS_REPO_SLUG"
#      description: "Build submitted via Travis CI"
#    notification_email:    "malak.jiri@gmail.com"
#    build_command_prepend:
#    build_command:         "travis/build.sh scan"
#    branch_pattern:        coverity_scan
